# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

epaKernelSmoothingCurve <- function(U, T, Y, b, n_obs_min) {
    .Call('_funestim_epaKernelSmoothingCurve', PACKAGE = 'funestim', U, T, Y, b, n_obs_min)
}

uniKernelSmoothingCurve <- function(U, T, Y, b, n_obs_min) {
    .Call('_funestim_uniKernelSmoothingCurve', PACKAGE = 'funestim', U, T, Y, b, n_obs_min)
}

biweightKernelSmoothingCurve <- function(U, T, Y, b, n_obs_min) {
    .Call('_funestim_biweightKernelSmoothingCurve', PACKAGE = 'funestim', U, T, Y, b, n_obs_min)
}

estimateSigma <- function(curves) {
    .Call('_funestim_estimateSigma', PACKAGE = 'funestim', curves)
}

